---
title: "wrangling practice"
author: "Felicia Cruz"
date: "8/18/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
sf_ghg <- read_csv(here("data", "sf_ghg.csv"))
library(palmerpenguins)
```

Summary tables
```{r}
sf_summary_sector <- sf_ghg %>% 
  group_by(Sector_General) %>% 
  summarize(total_ghg_em = sum(Emissions_mtCO2e, na.rm = TRUE))

sf_summary_year_comm <- sf_ghg %>% 
  group_by(Calendar_Year, Commodity_Type) %>% 
  summarize(total_ghg_em = sum(Emissions_mtCO2e, na.rm = TRUE))

sf_summary_3 <- sf_ghg %>%
  filter(Calendar_Year >= 2005) %>% 
  filter(str_detect(Sector_Detail2, pattern = "PG&E")) %>% 
  select(Calendar_Year, Sector_Detail2, Emissions_mtCO2e)

sf_summary_sector_year <- sf_ghg %>% 
  group_by(Sector_General, Calendar_Year) %>% 
  summarize(total_emissions = sum(Emissions_mtCO2e))
```


### Visualization 
```{r}
graph_data <- sf_summary_sector_year %>% filter(Sector_General == "Buildings" | Sector_General == "Transportation") 



ggplot(data = graph_data, aes(x = Calendar_Year, y = total_emissions)) +
  geom_line(aes(color = Sector_General)) +
  geom_text(data = filter(graph_data, Calendar_Year == max(Calendar_Year)), aes(label = Sector_General)) +
  labs(x = "Year", 
       y = "GHG Emissions (mtCO2e)",
       title = "GHG Emissions: Buildings vs. Transportation Sector",
       subtitle = "San Francisco (1990-2019)",
       color = "Sector") +
  theme(
    plot.background = element_rect(fill = "lightblue2")
  )

ggsave(here("pretty_plot.jpg"))
```
```{r, fig.alt = "Three histograms showing the body mass distribution of Adelie, Chinstrap, and Gentoo penguins"}
ggplot(penguins, aes(x = body_mass_g)) +
  geom_histogram() +
  facet_wrap(~species)


```

